#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#  include "keymap.h"
#endif

enum __layers {
  BASE,
  NAV,
  MOUSE,
  BUTTON,
  MEDIA,
  NUM,
  SYM,
  FUN,
  ADDITIONAL
};

/* BASE LAYER */
#define BL_A LGUI_T(KC_A)
#define BL_S LALT_T(KC_S)
#define BL_D LCTL_T(KC_D)
#define BL_F LSFT_T(KC_F)
#define BL_J LSFT_T(KC_J)
#define BL_K LCTL_T(KC_K)
#define BL_L LALT_T(KC_L)
#define BL_SC LGUI_T(KC_SCLN)
#define BL_Z LT(BUTTON,KC_Z)
#define BL_X RALT_T(KC_X)
#define BL_DT RALT_T(KC_DOT)
#define BL_SL LT(BUTTON,KC_SLSH)
#define BL_ESC LT(MEDIA,KC_ESC)
#define BL_SPC LT(NAV,KC_SPC)
#define BL_TAB LT(MOUSE,KC_TAB)
#define BL_ENT LT(SYM,KC_ENT)
#define BL_BSPC LT(NUM,KC_BSPC)
#define BL_DEL LT(FUN,KC_DEL)


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [BASE] = LAYOUT(
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //| Q       | W       | E       | R       | T       |     | Y       | U       | I       | O       | P       |
      KC_Q    , KC_W    , KC_E    , KC_R    , KC_T    ,       KC_Y    , KC_U    , KC_I    , KC_O    , KC_P    ,
  //├─────────┼─────────┼─────────┼─────────┼─────────┤     ├─────────┼─────────┼─────────┼─────────┼─────────┤
  //| A L_GUI | S L_ALT | D L_CTRL| F L_SHFT| G       |     | H       | J L_SHFT| K L_CTRL| L L_ALT | ; :     |
      BL_A    , BL_S    , BL_D    , BL_F    , KC_G    ,       KC_H    , BL_J    , BL_K    , BL_L    , BL_SC   ,
  //├─────────┼─────────┼─────────┼─────────┼─────────┤     ├─────────┼─────────┼─────────┼─────────┼─────────┤
  //| Z (BTTN)| X R_ALT | C       | V       | B       |     | N       | M       | ,  <    | .  >    | /  ?    |     
      BL_Z    , BL_X    , KC_C    , KC_V    , KC_B    ,       KC_N    , KC_M    , KC_COMM , BL_DT   , BL_SL   ,
  //└─────────┴─────────┼─────────┼─────────┼─────────┤     ├─────────┼─────────┼─────────┼─────────┴─────────┘
  //                    | ESC     | SPC     | TAB     |     | ENT     | BSPC    | DEL     | 
  //                    | (MEDIA) | (NAV)   | (MOUSE) |     | (SYM)   | (NUM)   | (FUN)   | 
                         BL_ESC   , BL_SPC  , BL_TAB  ,       BL_ENT  , BL_BSPC , BL_DEL 
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘
  ),

  [NAV] = LAYOUT(
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //| BOOT    | REBOOT  |         |         |         |     | REDO    | PASTE   | COPY    | CUT     | UNDO    |
      QK_BOOT ,QK_REBOOT, KC_NO   , KC_NO   , KC_NO   ,       KC_AGIN , KC_PASTE, KC_COPY , KC_CUT  , KC_UNDO ,
  //| L_GUI   | L_ALT   | L_CTRL  | L_SHFT  |         |     | CAPSLOCK|    ◀   |    ▼    |    ▲    |    ▶   |
      KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_NO   ,       KC_CAPS , KC_LEFT , KC_DOWN , KC_UP   , KC_RGHT ,
  //|         |         |         |         |         |     | INSERT  | HOME    | PG DOWN | PG UP   | END     |
      KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   ,       KC_INS  , KC_HOME , KC_PGDN , KC_PGUP , KC_END  ,
  //└─────────┴─────────┼         |         |         |     | ENT     | BSPC    | DEL     ┼─────────┴─────────┘
                          KC_NO   , KC_NO   , KC_NO   ,       KC_ENT  , KC_BSPC , KC_DEL  
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘
  ),             
 
  [MOUSE] = LAYOUT(
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //|         |         |         |         |         |     | REDO    | PASTE   | COPY    | CUT     | UNDO    |
      KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,       KC_AGIN , KC_PASTE, KC_COPY , KC_CUT  , KC_UNDO ,
  //| L_GUI   | L_ALT   | L_CTRL  | L_SHFT  |         |     |         |    ⇐   |    ⇓    |    ⇑    |    ⇒   |
      KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_NO   ,       KC_NO   , MS_LEFT , MS_DOWN , MS_UP , MS_RGHT ,
  //|         |         |         |         |         |     |         |    ←    |    ↓    |    ↑    |    →    |
      KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   ,       KC_NO   , MS_WHLL , MS_WHLD , MS_WHLU , MS_WHLR ,
  //└─────────┴─────────┼         |         |         |     | RGHT BUT| LFT BUT | MID BUT ┼─────────┴─────────┘
                          KC_NO   , KC_NO   , KC_NO   ,       KC_BTN2 , KC_BTN1 , KC_BTN3  
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘  
  ),

  [BUTTON] = LAYOUT(            
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //|         |         |         |         |         |     | REDO    | PASTE   | COPY    | CUT     | UNDO    |
      KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,       KC_AGIN , KC_PASTE, KC_COPY , KC_CUT  , KC_UNDO ,
  //| L_GUI   | L_ALT   | L_CTRL  | L_SHFT  |         |     |         | R_SHFT  | R_CTRL  | R_ALT   | R_GUI   |
      KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_NO   ,       KC_NO   , KC_RSFT , KC_RCTL , KC_RALT , KC_RGUI ,
  //|         |         |         |         |         |     | REDO    | PASTE   | COPY    | CUT     | UNDO    |
      KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   ,       KC_AGIN , KC_PASTE, KC_COPY , KC_CUT  , KC_UNDO ,
  //└─────────┴─────────┼ MS M BTN| MS L BTN| MS R BTN|     | MS R BTN| MS L BTN| MS M BTN┼─────────┴─────────┘
                          KC_BTN3 , KC_BTN1 , KC_BTN2 ,       KC_BTN2 , KC_BTN1 , KC_BTN3  
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘  
  ),

  [MEDIA] = LAYOUT(
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //|         |         |         |         |         |     | RGB TOG | RGB MOD | RGB HUE | RGB SAT | RGB VAL |
      KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,       RM_TOGG , RM_NEXT , RM_HUEU , RM_SATU , RM_VALU ,
  //| L_GUI   | L_ALT   | L_CTRL  | L_SHFT  |         |     | EP TOG  | PREV    | VOL DWN | VOL UP  | NEXT    |
      KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_NO   ,       KC_PWR  , KC_MPRV , KC_VOLD , KC_VOLU , KC_MNXT ,
  //|         |         |         |         |         |     | OUT TOG |  BT 0   |  BT 1   |  BT 2   |  BT 3   |
      KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   ,       AU_TOGG , BT_PRF1 , BT_PRF2 , BT_PRF3 , BT_PRF4 ,
  //└─────────┴─────────┼         |         |         |     | STOP    | PLAY/PS | MUTE    ┼─────────┴─────────┘
                          KC_NO   , KC_NO   , KC_NO   ,       KC_MSTP , KC_MPLY , KC_MUTE  
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘  
  ),

  [NUM] = LAYOUT(
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //|  [   {  |  7   &  |  8   *  |  9   (  |  ]   }  |     |         |         |         |         |         |
      KC_LBRC , KC_7    , KC_8    , KC_9    , KC_RBRC ,       KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,
  //|  ;   :  |  4   $  |  5   %  |  6   ^  |  +   =  |     |         | R_SHFT  | R_CTRL  | R_ALT   | R_GUI   |
      KC_SCLN , KC_4    , KC_5    , KC_6    , KC_EQL  ,       KC_NO   , KC_RSFT , KC_RCTL , KC_RALT , KC_RGUI ,
  //|  `   ~  |  1   !  |  2   @  |  3   #  |  \   |  |     |         |         |         |         |         |
      KC_GRV  , KC_1    , KC_2    , KC_3    , KC_BSLS ,       KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,
  //└─────────┴─────────┼  .   >  |  0   )  |  -   _  |     |         |         |         ┼─────────┴─────────┘
                          KC_DOT  , KC_0    , KC_MINS ,       KC_NO , KC_NO   , KC_NO
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘  
  ),

  [SYM] = LAYOUT(
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //|    {    |    &    |    *    |   (     |    }    |     |         |         |         |         |         |
      KC_LCBR , KC_AMPR , KC_ASTR , KC_LPRN , KC_RCBR ,       KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,
  //|    :    |    $    |    %    |    ^    |    +    |     |         | R_SHFT  | R_CTRL  | R_ALT   | R_GUI   |
      KC_COLN , KC_DLR  , KC_PERC , KC_CIRC , KC_PLUS ,       KC_NO   , KC_RSFT , KC_RCTL , KC_RALT , KC_RGUI ,
  //|    ~    |    !    |    @    |    #    |    |    |     |         |         |         |         |         |
      KC_TILD , KC_EXLM , KC_AT   , KC_HASH , KC_PIPE ,       KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,
  //└─────────┴─────────┼    (    |    )    |    _    |     |         |         |         ┼─────────┴─────────┘
                          KC_LPRN , KC_RPRN , KC_UNDS ,       KC_NO , KC_NO   , KC_NO
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘  
  ),

  [FUN] = LAYOUT(
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //|  F12    |  F7     |  F8     |  F9     | PRTSCN  |     |         |         |         |         |         |
      KC_F12  , KC_F7   , KC_F8   , KC_F9   , KC_PSCR ,       KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,
  //|  F11    |  F4     |  F5     |  F6     | SCRL LK |     |         | R_SHFT  | R_CTRL  | R_ALT   | R_GUI   |
      KC_F11  , KC_F4   , KC_F5   , KC_F6   , KC_SCRL ,       KC_NO   , KC_RSFT , KC_RCTL , KC_RALT , KC_RGUI ,
  //|  F10    |  F1     |  F2     |  F3     | PAUS BRK|     |         |         |         |         |         |
      KC_F10  , KC_F1   , KC_F2   , KC_F3   , KC_PAUS ,       KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,
  //└─────────┴─────────┼ APPLICA | SPACE   | TAB     |     |         |         |         ┼─────────┴─────────┘
                          KC_APP  , KC_SPC  , KC_TAB ,       KC_NO    , KC_NO   , KC_NO
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘  
  ),
  
  [ADDITIONAL] = LAYOUT(            
  //┌─────────┬─────────┬─────────┬─────────┬─────────┐     ┌─────────┬─────────┬─────────┬─────────┬─────────┐
  //|  BOOT   |  TAP    |  EXTRA  |  BASE   |         |     |         |  BASE   |  EXTRA  |  TAP    |  BOOT   |
      QK_BOOT , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,       KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , QK_BOOT ,
  //|         |         |         |         |         |     |         |         |         |         |         |
      KC_LGUI , KC_LALT , KC_LCTL , KC_LSFT , KC_NO   ,       KC_NO   , KC_RSFT , KC_RCTL , KC_RALT , KC_RGUI ,
  //|         |         |   OPP   |  CURR   |         |     |         |  CURR   |  OPP    |         |         |
      KC_NO   , KC_NO   , KC_NO   , KC_NO   , KC_NO   ,       KC_NO   , KC_NO   ,  KC_NO  ,  KC_NO  , KC_NO   ,
  //└─────────┴─────────┼         |         |         |     |         |         |         ┼─────────┴─────────┘
                          KC_NO   , KC_NO   , KC_NO   ,      KC_NO    , KC_NO   , KC_NO
  //                    └─────────┴─────────┴─────────┘     └─────────┴─────────┴─────────┘  
  ),


};

const key_override_t *key_overrides[] = {
 
};

tap_dance_action_t tap_dance_actions[] = {
 
};




